// megafunction wizard: %ALTIOBUF%
// GENERATION: STANDARD
// VERSION: WM1.0
// MODULE: altiobuf_out 

// ============================================================
// File Name: lvds_altiobuf17_o.v
// Megafunction Name(s):
// 			altiobuf_out
//
// Simulation Library Files(s):
// 			cyclonev
// ============================================================
// ************************************************************
// THIS IS A WIZARD-GENERATED FILE. DO NOT EDIT THIS FILE!
//
// 15.0.2 Build 153 07/15/2015 SJ Full Version
// ************************************************************


//Copyright (C) 1991-2015 Altera Corporation. All rights reserved.
//Your use of Altera Corporation's design tools, logic functions 
//and other software and tools, and its AMPP partner logic 
//functions, and any output files from any of the foregoing 
//(including device programming or simulation files), and any 
//associated documentation or information are expressly subject 
//to the terms and conditions of the Altera Program License 
//Subscription Agreement, the Altera Quartus II License Agreement,
//the Altera MegaCore Function License Agreement, or other 
//applicable license agreement, including, without limitation, 
//that your use is for the sole purpose of programming logic 
//devices manufactured by Altera and sold by Altera or its 
//authorized distributors.  Please refer to the applicable 
//agreement for further details.


//altiobuf_out CBX_AUTO_BLACKBOX="ALL" DEVICE_FAMILY="Cyclone V" ENABLE_BUS_HOLD="FALSE" LEFT_SHIFT_SERIES_TERMINATION_CONTROL="FALSE" NUMBER_OF_CHANNELS=17 OPEN_DRAIN_OUTPUT="FALSE" PSEUDO_DIFFERENTIAL_MODE="TRUE" USE_DIFFERENTIAL_MODE="TRUE" USE_OE="FALSE" USE_TERMINATION_CONTROL="FALSE" datain dataout dataout_b
//VERSION_BEGIN 15.0 cbx_altiobuf_out 2015:07:15:18:07:03:SJ cbx_mgl 2015:07:15:18:09:04:SJ cbx_stratixiii 2015:07:15:18:07:03:SJ cbx_stratixv 2015:07:15:18:07:03:SJ  VERSION_END
// synthesis VERILOG_INPUT_VERSION VERILOG_2001
// altera message_off 10463


//synthesis_resources = cyclonev_io_obuf 34 cyclonev_pseudo_diff_out 17 
//synopsys translate_off
`timescale 1 ps / 1 ps
//synopsys translate_on
module  lvds_altiobuf17_o_iobuf_out_akt
	( 
	datain,
	dataout,
	dataout_b) ;
	input   [16:0]  datain;
	output   [16:0]  dataout;
	output   [16:0]  dataout_b;

	wire  [16:0]   wire_obuf_ba_i;
	wire  [16:0]   wire_obuf_ba_o;
	wire  [16:0]   wire_obuf_ba_oe;
	wire  [16:0]   wire_obufa_i;
	wire  [16:0]   wire_obufa_o;
	wire  [16:0]   wire_obufa_oe;
	wire  [16:0]   wire_pseudo_diffa_i;
	wire  [16:0]   wire_pseudo_diffa_o;
	wire  [16:0]   wire_pseudo_diffa_obar;
	wire  [16:0]   wire_pseudo_diffa_oebout;
	wire  [16:0]   wire_pseudo_diffa_oein;
	wire  [16:0]   wire_pseudo_diffa_oeout;
	wire  [16:0]  oe_w;

	cyclonev_io_obuf   obuf_ba_0
	( 
	.i(wire_obuf_ba_i[0:0]),
	.o(wire_obuf_ba_o[0:0]),
	.obar(),
	.oe(wire_obuf_ba_oe[0:0])
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.dynamicterminationcontrol(1'b0),
	.parallelterminationcontrol({16{1'b0}}),
	.seriesterminationcontrol({16{1'b0}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devoe(1'b1)
	// synopsys translate_on
	);
	defparam
		obuf_ba_0.bus_hold = "false",
		obuf_ba_0.open_drain_output = "false",
		obuf_ba_0.lpm_type = "cyclonev_io_obuf";
	cyclonev_io_obuf   obuf_ba_1
	( 
	.i(wire_obuf_ba_i[1:1]),
	.o(wire_obuf_ba_o[1:1]),
	.obar(),
	.oe(wire_obuf_ba_oe[1:1])
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.dynamicterminationcontrol(1'b0),
	.parallelterminationcontrol({16{1'b0}}),
	.seriesterminationcontrol({16{1'b0}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devoe(1'b1)
	// synopsys translate_on
	);
	defparam
		obuf_ba_1.bus_hold = "false",
		obuf_ba_1.open_drain_output = "false",
		obuf_ba_1.lpm_type = "cyclonev_io_obuf";
	cyclonev_io_obuf   obuf_ba_2
	( 
	.i(wire_obuf_ba_i[2:2]),
	.o(wire_obuf_ba_o[2:2]),
	.obar(),
	.oe(wire_obuf_ba_oe[2:2])
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.dynamicterminationcontrol(1'b0),
	.parallelterminationcontrol({16{1'b0}}),
	.seriesterminationcontrol({16{1'b0}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devoe(1'b1)
	// synopsys translate_on
	);
	defparam
		obuf_ba_2.bus_hold = "false",
		obuf_ba_2.open_drain_output = "false",
		obuf_ba_2.lpm_type = "cyclonev_io_obuf";
	cyclonev_io_obuf   obuf_ba_3
	( 
	.i(wire_obuf_ba_i[3:3]),
	.o(wire_obuf_ba_o[3:3]),
	.obar(),
	.oe(wire_obuf_ba_oe[3:3])
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.dynamicterminationcontrol(1'b0),
	.parallelterminationcontrol({16{1'b0}}),
	.seriesterminationcontrol({16{1'b0}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devoe(1'b1)
	// synopsys translate_on
	);
	defparam
		obuf_ba_3.bus_hold = "false",
		obuf_ba_3.open_drain_output = "false",
		obuf_ba_3.lpm_type = "cyclonev_io_obuf";
	cyclonev_io_obuf   obuf_ba_4
	( 
	.i(wire_obuf_ba_i[4:4]),
	.o(wire_obuf_ba_o[4:4]),
	.obar(),
	.oe(wire_obuf_ba_oe[4:4])
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.dynamicterminationcontrol(1'b0),
	.parallelterminationcontrol({16{1'b0}}),
	.seriesterminationcontrol({16{1'b0}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devoe(1'b1)
	// synopsys translate_on
	);
	defparam
		obuf_ba_4.bus_hold = "false",
		obuf_ba_4.open_drain_output = "false",
		obuf_ba_4.lpm_type = "cyclonev_io_obuf";
	cyclonev_io_obuf   obuf_ba_5
	( 
	.i(wire_obuf_ba_i[5:5]),
	.o(wire_obuf_ba_o[5:5]),
	.obar(),
	.oe(wire_obuf_ba_oe[5:5])
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.dynamicterminationcontrol(1'b0),
	.parallelterminationcontrol({16{1'b0}}),
	.seriesterminationcontrol({16{1'b0}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devoe(1'b1)
	// synopsys translate_on
	);
	defparam
		obuf_ba_5.bus_hold = "false",
		obuf_ba_5.open_drain_output = "false",
		obuf_ba_5.lpm_type = "cyclonev_io_obuf";
	cyclonev_io_obuf   obuf_ba_6
	( 
	.i(wire_obuf_ba_i[6:6]),
	.o(wire_obuf_ba_o[6:6]),
	.obar(),
	.oe(wire_obuf_ba_oe[6:6])
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.dynamicterminationcontrol(1'b0),
	.parallelterminationcontrol({16{1'b0}}),
	.seriesterminationcontrol({16{1'b0}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devoe(1'b1)
	// synopsys translate_on
	);
	defparam
		obuf_ba_6.bus_hold = "false",
		obuf_ba_6.open_drain_output = "false",
		obuf_ba_6.lpm_type = "cyclonev_io_obuf";
	cyclonev_io_obuf   obuf_ba_7
	( 
	.i(wire_obuf_ba_i[7:7]),
	.o(wire_obuf_ba_o[7:7]),
	.obar(),
	.oe(wire_obuf_ba_oe[7:7])
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.dynamicterminationcontrol(1'b0),
	.parallelterminationcontrol({16{1'b0}}),
	.seriesterminationcontrol({16{1'b0}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devoe(1'b1)
	// synopsys translate_on
	);
	defparam
		obuf_ba_7.bus_hold = "false",
		obuf_ba_7.open_drain_output = "false",
		obuf_ba_7.lpm_type = "cyclonev_io_obuf";
	cyclonev_io_obuf   obuf_ba_8
	( 
	.i(wire_obuf_ba_i[8:8]),
	.o(wire_obuf_ba_o[8:8]),
	.obar(),
	.oe(wire_obuf_ba_oe[8:8])
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.dynamicterminationcontrol(1'b0),
	.parallelterminationcontrol({16{1'b0}}),
	.seriesterminationcontrol({16{1'b0}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devoe(1'b1)
	// synopsys translate_on
	);
	defparam
		obuf_ba_8.bus_hold = "false",
		obuf_ba_8.open_drain_output = "false",
		obuf_ba_8.lpm_type = "cyclonev_io_obuf";
	cyclonev_io_obuf   obuf_ba_9
	( 
	.i(wire_obuf_ba_i[9:9]),
	.o(wire_obuf_ba_o[9:9]),
	.obar(),
	.oe(wire_obuf_ba_oe[9:9])
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.dynamicterminationcontrol(1'b0),
	.parallelterminationcontrol({16{1'b0}}),
	.seriesterminationcontrol({16{1'b0}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devoe(1'b1)
	// synopsys translate_on
	);
	defparam
		obuf_ba_9.bus_hold = "false",
		obuf_ba_9.open_drain_output = "false",
		obuf_ba_9.lpm_type = "cyclonev_io_obuf";
	cyclonev_io_obuf   obuf_ba_10
	( 
	.i(wire_obuf_ba_i[10:10]),
	.o(wire_obuf_ba_o[10:10]),
	.obar(),
	.oe(wire_obuf_ba_oe[10:10])
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.dynamicterminationcontrol(1'b0),
	.parallelterminationcontrol({16{1'b0}}),
	.seriesterminationcontrol({16{1'b0}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devoe(1'b1)
	// synopsys translate_on
	);
	defparam
		obuf_ba_10.bus_hold = "false",
		obuf_ba_10.open_drain_output = "false",
		obuf_ba_10.lpm_type = "cyclonev_io_obuf";
	cyclonev_io_obuf   obuf_ba_11
	( 
	.i(wire_obuf_ba_i[11:11]),
	.o(wire_obuf_ba_o[11:11]),
	.obar(),
	.oe(wire_obuf_ba_oe[11:11])
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.dynamicterminationcontrol(1'b0),
	.parallelterminationcontrol({16{1'b0}}),
	.seriesterminationcontrol({16{1'b0}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devoe(1'b1)
	// synopsys translate_on
	);
	defparam
		obuf_ba_11.bus_hold = "false",
		obuf_ba_11.open_drain_output = "false",
		obuf_ba_11.lpm_type = "cyclonev_io_obuf";
	cyclonev_io_obuf   obuf_ba_12
	( 
	.i(wire_obuf_ba_i[12:12]),
	.o(wire_obuf_ba_o[12:12]),
	.obar(),
	.oe(wire_obuf_ba_oe[12:12])
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.dynamicterminationcontrol(1'b0),
	.parallelterminationcontrol({16{1'b0}}),
	.seriesterminationcontrol({16{1'b0}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devoe(1'b1)
	// synopsys translate_on
	);
	defparam
		obuf_ba_12.bus_hold = "false",
		obuf_ba_12.open_drain_output = "false",
		obuf_ba_12.lpm_type = "cyclonev_io_obuf";
	cyclonev_io_obuf   obuf_ba_13
	( 
	.i(wire_obuf_ba_i[13:13]),
	.o(wire_obuf_ba_o[13:13]),
	.obar(),
	.oe(wire_obuf_ba_oe[13:13])
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.dynamicterminationcontrol(1'b0),
	.parallelterminationcontrol({16{1'b0}}),
	.seriesterminationcontrol({16{1'b0}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devoe(1'b1)
	// synopsys translate_on
	);
	defparam
		obuf_ba_13.bus_hold = "false",
		obuf_ba_13.open_drain_output = "false",
		obuf_ba_13.lpm_type = "cyclonev_io_obuf";
	cyclonev_io_obuf   obuf_ba_14
	( 
	.i(wire_obuf_ba_i[14:14]),
	.o(wire_obuf_ba_o[14:14]),
	.obar(),
	.oe(wire_obuf_ba_oe[14:14])
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.dynamicterminationcontrol(1'b0),
	.parallelterminationcontrol({16{1'b0}}),
	.seriesterminationcontrol({16{1'b0}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devoe(1'b1)
	// synopsys translate_on
	);
	defparam
		obuf_ba_14.bus_hold = "false",
		obuf_ba_14.open_drain_output = "false",
		obuf_ba_14.lpm_type = "cyclonev_io_obuf";
	cyclonev_io_obuf   obuf_ba_15
	( 
	.i(wire_obuf_ba_i[15:15]),
	.o(wire_obuf_ba_o[15:15]),
	.obar(),
	.oe(wire_obuf_ba_oe[15:15])
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.dynamicterminationcontrol(1'b0),
	.parallelterminationcontrol({16{1'b0}}),
	.seriesterminationcontrol({16{1'b0}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devoe(1'b1)
	// synopsys translate_on
	);
	defparam
		obuf_ba_15.bus_hold = "false",
		obuf_ba_15.open_drain_output = "false",
		obuf_ba_15.lpm_type = "cyclonev_io_obuf";
	cyclonev_io_obuf   obuf_ba_16
	( 
	.i(wire_obuf_ba_i[16:16]),
	.o(wire_obuf_ba_o[16:16]),
	.obar(),
	.oe(wire_obuf_ba_oe[16:16])
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.dynamicterminationcontrol(1'b0),
	.parallelterminationcontrol({16{1'b0}}),
	.seriesterminationcontrol({16{1'b0}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devoe(1'b1)
	// synopsys translate_on
	);
	defparam
		obuf_ba_16.bus_hold = "false",
		obuf_ba_16.open_drain_output = "false",
		obuf_ba_16.lpm_type = "cyclonev_io_obuf";
	assign
		wire_obuf_ba_i = wire_pseudo_diffa_obar,
		wire_obuf_ba_oe = {(~ wire_pseudo_diffa_oebout[16]), (~ wire_pseudo_diffa_oebout[15]), (~ wire_pseudo_diffa_oebout[14]), (~ wire_pseudo_diffa_oebout[13]), (~ wire_pseudo_diffa_oebout[12]), (~ wire_pseudo_diffa_oebout[11]), (~ wire_pseudo_diffa_oebout[10]), (~ wire_pseudo_diffa_oebout[9]), (~ wire_pseudo_diffa_oebout[8]), (~ wire_pseudo_diffa_oebout[7]), (~ wire_pseudo_diffa_oebout[6]), (~ wire_pseudo_diffa_oebout[5]), (~ wire_pseudo_diffa_oebout[4]), (~ wire_pseudo_diffa_oebout[3]), (~ wire_pseudo_diffa_oebout[2]), (~ wire_pseudo_diffa_oebout[1]), (~ wire_pseudo_diffa_oebout[0])};
	cyclonev_io_obuf   obufa_0
	( 
	.i(wire_obufa_i[0:0]),
	.o(wire_obufa_o[0:0]),
	.obar(),
	.oe(wire_obufa_oe[0:0])
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.dynamicterminationcontrol(1'b0),
	.parallelterminationcontrol({16{1'b0}}),
	.seriesterminationcontrol({16{1'b0}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devoe(1'b1)
	// synopsys translate_on
	);
	defparam
		obufa_0.bus_hold = "false",
		obufa_0.open_drain_output = "false",
		obufa_0.lpm_type = "cyclonev_io_obuf";
	cyclonev_io_obuf   obufa_1
	( 
	.i(wire_obufa_i[1:1]),
	.o(wire_obufa_o[1:1]),
	.obar(),
	.oe(wire_obufa_oe[1:1])
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.dynamicterminationcontrol(1'b0),
	.parallelterminationcontrol({16{1'b0}}),
	.seriesterminationcontrol({16{1'b0}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devoe(1'b1)
	// synopsys translate_on
	);
	defparam
		obufa_1.bus_hold = "false",
		obufa_1.open_drain_output = "false",
		obufa_1.lpm_type = "cyclonev_io_obuf";
	cyclonev_io_obuf   obufa_2
	( 
	.i(wire_obufa_i[2:2]),
	.o(wire_obufa_o[2:2]),
	.obar(),
	.oe(wire_obufa_oe[2:2])
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.dynamicterminationcontrol(1'b0),
	.parallelterminationcontrol({16{1'b0}}),
	.seriesterminationcontrol({16{1'b0}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devoe(1'b1)
	// synopsys translate_on
	);
	defparam
		obufa_2.bus_hold = "false",
		obufa_2.open_drain_output = "false",
		obufa_2.lpm_type = "cyclonev_io_obuf";
	cyclonev_io_obuf   obufa_3
	( 
	.i(wire_obufa_i[3:3]),
	.o(wire_obufa_o[3:3]),
	.obar(),
	.oe(wire_obufa_oe[3:3])
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.dynamicterminationcontrol(1'b0),
	.parallelterminationcontrol({16{1'b0}}),
	.seriesterminationcontrol({16{1'b0}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devoe(1'b1)
	// synopsys translate_on
	);
	defparam
		obufa_3.bus_hold = "false",
		obufa_3.open_drain_output = "false",
		obufa_3.lpm_type = "cyclonev_io_obuf";
	cyclonev_io_obuf   obufa_4
	( 
	.i(wire_obufa_i[4:4]),
	.o(wire_obufa_o[4:4]),
	.obar(),
	.oe(wire_obufa_oe[4:4])
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.dynamicterminationcontrol(1'b0),
	.parallelterminationcontrol({16{1'b0}}),
	.seriesterminationcontrol({16{1'b0}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devoe(1'b1)
	// synopsys translate_on
	);
	defparam
		obufa_4.bus_hold = "false",
		obufa_4.open_drain_output = "false",
		obufa_4.lpm_type = "cyclonev_io_obuf";
	cyclonev_io_obuf   obufa_5
	( 
	.i(wire_obufa_i[5:5]),
	.o(wire_obufa_o[5:5]),
	.obar(),
	.oe(wire_obufa_oe[5:5])
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.dynamicterminationcontrol(1'b0),
	.parallelterminationcontrol({16{1'b0}}),
	.seriesterminationcontrol({16{1'b0}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devoe(1'b1)
	// synopsys translate_on
	);
	defparam
		obufa_5.bus_hold = "false",
		obufa_5.open_drain_output = "false",
		obufa_5.lpm_type = "cyclonev_io_obuf";
	cyclonev_io_obuf   obufa_6
	( 
	.i(wire_obufa_i[6:6]),
	.o(wire_obufa_o[6:6]),
	.obar(),
	.oe(wire_obufa_oe[6:6])
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.dynamicterminationcontrol(1'b0),
	.parallelterminationcontrol({16{1'b0}}),
	.seriesterminationcontrol({16{1'b0}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devoe(1'b1)
	// synopsys translate_on
	);
	defparam
		obufa_6.bus_hold = "false",
		obufa_6.open_drain_output = "false",
		obufa_6.lpm_type = "cyclonev_io_obuf";
	cyclonev_io_obuf   obufa_7
	( 
	.i(wire_obufa_i[7:7]),
	.o(wire_obufa_o[7:7]),
	.obar(),
	.oe(wire_obufa_oe[7:7])
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.dynamicterminationcontrol(1'b0),
	.parallelterminationcontrol({16{1'b0}}),
	.seriesterminationcontrol({16{1'b0}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devoe(1'b1)
	// synopsys translate_on
	);
	defparam
		obufa_7.bus_hold = "false",
		obufa_7.open_drain_output = "false",
		obufa_7.lpm_type = "cyclonev_io_obuf";
	cyclonev_io_obuf   obufa_8
	( 
	.i(wire_obufa_i[8:8]),
	.o(wire_obufa_o[8:8]),
	.obar(),
	.oe(wire_obufa_oe[8:8])
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.dynamicterminationcontrol(1'b0),
	.parallelterminationcontrol({16{1'b0}}),
	.seriesterminationcontrol({16{1'b0}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devoe(1'b1)
	// synopsys translate_on
	);
	defparam
		obufa_8.bus_hold = "false",
		obufa_8.open_drain_output = "false",
		obufa_8.lpm_type = "cyclonev_io_obuf";
	cyclonev_io_obuf   obufa_9
	( 
	.i(wire_obufa_i[9:9]),
	.o(wire_obufa_o[9:9]),
	.obar(),
	.oe(wire_obufa_oe[9:9])
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.dynamicterminationcontrol(1'b0),
	.parallelterminationcontrol({16{1'b0}}),
	.seriesterminationcontrol({16{1'b0}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devoe(1'b1)
	// synopsys translate_on
	);
	defparam
		obufa_9.bus_hold = "false",
		obufa_9.open_drain_output = "false",
		obufa_9.lpm_type = "cyclonev_io_obuf";
	cyclonev_io_obuf   obufa_10
	( 
	.i(wire_obufa_i[10:10]),
	.o(wire_obufa_o[10:10]),
	.obar(),
	.oe(wire_obufa_oe[10:10])
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.dynamicterminationcontrol(1'b0),
	.parallelterminationcontrol({16{1'b0}}),
	.seriesterminationcontrol({16{1'b0}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devoe(1'b1)
	// synopsys translate_on
	);
	defparam
		obufa_10.bus_hold = "false",
		obufa_10.open_drain_output = "false",
		obufa_10.lpm_type = "cyclonev_io_obuf";
	cyclonev_io_obuf   obufa_11
	( 
	.i(wire_obufa_i[11:11]),
	.o(wire_obufa_o[11:11]),
	.obar(),
	.oe(wire_obufa_oe[11:11])
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.dynamicterminationcontrol(1'b0),
	.parallelterminationcontrol({16{1'b0}}),
	.seriesterminationcontrol({16{1'b0}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devoe(1'b1)
	// synopsys translate_on
	);
	defparam
		obufa_11.bus_hold = "false",
		obufa_11.open_drain_output = "false",
		obufa_11.lpm_type = "cyclonev_io_obuf";
	cyclonev_io_obuf   obufa_12
	( 
	.i(wire_obufa_i[12:12]),
	.o(wire_obufa_o[12:12]),
	.obar(),
	.oe(wire_obufa_oe[12:12])
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.dynamicterminationcontrol(1'b0),
	.parallelterminationcontrol({16{1'b0}}),
	.seriesterminationcontrol({16{1'b0}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devoe(1'b1)
	// synopsys translate_on
	);
	defparam
		obufa_12.bus_hold = "false",
		obufa_12.open_drain_output = "false",
		obufa_12.lpm_type = "cyclonev_io_obuf";
	cyclonev_io_obuf   obufa_13
	( 
	.i(wire_obufa_i[13:13]),
	.o(wire_obufa_o[13:13]),
	.obar(),
	.oe(wire_obufa_oe[13:13])
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.dynamicterminationcontrol(1'b0),
	.parallelterminationcontrol({16{1'b0}}),
	.seriesterminationcontrol({16{1'b0}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devoe(1'b1)
	// synopsys translate_on
	);
	defparam
		obufa_13.bus_hold = "false",
		obufa_13.open_drain_output = "false",
		obufa_13.lpm_type = "cyclonev_io_obuf";
	cyclonev_io_obuf   obufa_14
	( 
	.i(wire_obufa_i[14:14]),
	.o(wire_obufa_o[14:14]),
	.obar(),
	.oe(wire_obufa_oe[14:14])
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.dynamicterminationcontrol(1'b0),
	.parallelterminationcontrol({16{1'b0}}),
	.seriesterminationcontrol({16{1'b0}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devoe(1'b1)
	// synopsys translate_on
	);
	defparam
		obufa_14.bus_hold = "false",
		obufa_14.open_drain_output = "false",
		obufa_14.lpm_type = "cyclonev_io_obuf";
	cyclonev_io_obuf   obufa_15
	( 
	.i(wire_obufa_i[15:15]),
	.o(wire_obufa_o[15:15]),
	.obar(),
	.oe(wire_obufa_oe[15:15])
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.dynamicterminationcontrol(1'b0),
	.parallelterminationcontrol({16{1'b0}}),
	.seriesterminationcontrol({16{1'b0}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devoe(1'b1)
	// synopsys translate_on
	);
	defparam
		obufa_15.bus_hold = "false",
		obufa_15.open_drain_output = "false",
		obufa_15.lpm_type = "cyclonev_io_obuf";
	cyclonev_io_obuf   obufa_16
	( 
	.i(wire_obufa_i[16:16]),
	.o(wire_obufa_o[16:16]),
	.obar(),
	.oe(wire_obufa_oe[16:16])
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.dynamicterminationcontrol(1'b0),
	.parallelterminationcontrol({16{1'b0}}),
	.seriesterminationcontrol({16{1'b0}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devoe(1'b1)
	// synopsys translate_on
	);
	defparam
		obufa_16.bus_hold = "false",
		obufa_16.open_drain_output = "false",
		obufa_16.lpm_type = "cyclonev_io_obuf";
	assign
		wire_obufa_i = wire_pseudo_diffa_o,
		wire_obufa_oe = {(~ wire_pseudo_diffa_oeout[16]), (~ wire_pseudo_diffa_oeout[15]), (~ wire_pseudo_diffa_oeout[14]), (~ wire_pseudo_diffa_oeout[13]), (~ wire_pseudo_diffa_oeout[12]), (~ wire_pseudo_diffa_oeout[11]), (~ wire_pseudo_diffa_oeout[10]), (~ wire_pseudo_diffa_oeout[9]), (~ wire_pseudo_diffa_oeout[8]), (~ wire_pseudo_diffa_oeout[7]), (~ wire_pseudo_diffa_oeout[6]), (~ wire_pseudo_diffa_oeout[5]), (~ wire_pseudo_diffa_oeout[4]), (~ wire_pseudo_diffa_oeout[3]), (~ wire_pseudo_diffa_oeout[2]), (~ wire_pseudo_diffa_oeout[1]), (~ wire_pseudo_diffa_oeout[0])};
	cyclonev_pseudo_diff_out   pseudo_diffa_0
	( 
	.dtc(),
	.dtcbar(),
	.i(wire_pseudo_diffa_i[0:0]),
	.o(wire_pseudo_diffa_o[0:0]),
	.obar(wire_pseudo_diffa_obar[0:0]),
	.oebout(wire_pseudo_diffa_oebout[0:0]),
	.oein(wire_pseudo_diffa_oein[0:0]),
	.oeout(wire_pseudo_diffa_oeout[0:0])
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.dtcin(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	);
	cyclonev_pseudo_diff_out   pseudo_diffa_1
	( 
	.dtc(),
	.dtcbar(),
	.i(wire_pseudo_diffa_i[1:1]),
	.o(wire_pseudo_diffa_o[1:1]),
	.obar(wire_pseudo_diffa_obar[1:1]),
	.oebout(wire_pseudo_diffa_oebout[1:1]),
	.oein(wire_pseudo_diffa_oein[1:1]),
	.oeout(wire_pseudo_diffa_oeout[1:1])
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.dtcin(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	);
	cyclonev_pseudo_diff_out   pseudo_diffa_2
	( 
	.dtc(),
	.dtcbar(),
	.i(wire_pseudo_diffa_i[2:2]),
	.o(wire_pseudo_diffa_o[2:2]),
	.obar(wire_pseudo_diffa_obar[2:2]),
	.oebout(wire_pseudo_diffa_oebout[2:2]),
	.oein(wire_pseudo_diffa_oein[2:2]),
	.oeout(wire_pseudo_diffa_oeout[2:2])
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.dtcin(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	);
	cyclonev_pseudo_diff_out   pseudo_diffa_3
	( 
	.dtc(),
	.dtcbar(),
	.i(wire_pseudo_diffa_i[3:3]),
	.o(wire_pseudo_diffa_o[3:3]),
	.obar(wire_pseudo_diffa_obar[3:3]),
	.oebout(wire_pseudo_diffa_oebout[3:3]),
	.oein(wire_pseudo_diffa_oein[3:3]),
	.oeout(wire_pseudo_diffa_oeout[3:3])
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.dtcin(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	);
	cyclonev_pseudo_diff_out   pseudo_diffa_4
	( 
	.dtc(),
	.dtcbar(),
	.i(wire_pseudo_diffa_i[4:4]),
	.o(wire_pseudo_diffa_o[4:4]),
	.obar(wire_pseudo_diffa_obar[4:4]),
	.oebout(wire_pseudo_diffa_oebout[4:4]),
	.oein(wire_pseudo_diffa_oein[4:4]),
	.oeout(wire_pseudo_diffa_oeout[4:4])
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.dtcin(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	);
	cyclonev_pseudo_diff_out   pseudo_diffa_5
	( 
	.dtc(),
	.dtcbar(),
	.i(wire_pseudo_diffa_i[5:5]),
	.o(wire_pseudo_diffa_o[5:5]),
	.obar(wire_pseudo_diffa_obar[5:5]),
	.oebout(wire_pseudo_diffa_oebout[5:5]),
	.oein(wire_pseudo_diffa_oein[5:5]),
	.oeout(wire_pseudo_diffa_oeout[5:5])
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.dtcin(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	);
	cyclonev_pseudo_diff_out   pseudo_diffa_6
	( 
	.dtc(),
	.dtcbar(),
	.i(wire_pseudo_diffa_i[6:6]),
	.o(wire_pseudo_diffa_o[6:6]),
	.obar(wire_pseudo_diffa_obar[6:6]),
	.oebout(wire_pseudo_diffa_oebout[6:6]),
	.oein(wire_pseudo_diffa_oein[6:6]),
	.oeout(wire_pseudo_diffa_oeout[6:6])
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.dtcin(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	);
	cyclonev_pseudo_diff_out   pseudo_diffa_7
	( 
	.dtc(),
	.dtcbar(),
	.i(wire_pseudo_diffa_i[7:7]),
	.o(wire_pseudo_diffa_o[7:7]),
	.obar(wire_pseudo_diffa_obar[7:7]),
	.oebout(wire_pseudo_diffa_oebout[7:7]),
	.oein(wire_pseudo_diffa_oein[7:7]),
	.oeout(wire_pseudo_diffa_oeout[7:7])
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.dtcin(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	);
	cyclonev_pseudo_diff_out   pseudo_diffa_8
	( 
	.dtc(),
	.dtcbar(),
	.i(wire_pseudo_diffa_i[8:8]),
	.o(wire_pseudo_diffa_o[8:8]),
	.obar(wire_pseudo_diffa_obar[8:8]),
	.oebout(wire_pseudo_diffa_oebout[8:8]),
	.oein(wire_pseudo_diffa_oein[8:8]),
	.oeout(wire_pseudo_diffa_oeout[8:8])
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.dtcin(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	);
	cyclonev_pseudo_diff_out   pseudo_diffa_9
	( 
	.dtc(),
	.dtcbar(),
	.i(wire_pseudo_diffa_i[9:9]),
	.o(wire_pseudo_diffa_o[9:9]),
	.obar(wire_pseudo_diffa_obar[9:9]),
	.oebout(wire_pseudo_diffa_oebout[9:9]),
	.oein(wire_pseudo_diffa_oein[9:9]),
	.oeout(wire_pseudo_diffa_oeout[9:9])
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.dtcin(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	);
	cyclonev_pseudo_diff_out   pseudo_diffa_10
	( 
	.dtc(),
	.dtcbar(),
	.i(wire_pseudo_diffa_i[10:10]),
	.o(wire_pseudo_diffa_o[10:10]),
	.obar(wire_pseudo_diffa_obar[10:10]),
	.oebout(wire_pseudo_diffa_oebout[10:10]),
	.oein(wire_pseudo_diffa_oein[10:10]),
	.oeout(wire_pseudo_diffa_oeout[10:10])
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.dtcin(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	);
	cyclonev_pseudo_diff_out   pseudo_diffa_11
	( 
	.dtc(),
	.dtcbar(),
	.i(wire_pseudo_diffa_i[11:11]),
	.o(wire_pseudo_diffa_o[11:11]),
	.obar(wire_pseudo_diffa_obar[11:11]),
	.oebout(wire_pseudo_diffa_oebout[11:11]),
	.oein(wire_pseudo_diffa_oein[11:11]),
	.oeout(wire_pseudo_diffa_oeout[11:11])
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.dtcin(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	);
	cyclonev_pseudo_diff_out   pseudo_diffa_12
	( 
	.dtc(),
	.dtcbar(),
	.i(wire_pseudo_diffa_i[12:12]),
	.o(wire_pseudo_diffa_o[12:12]),
	.obar(wire_pseudo_diffa_obar[12:12]),
	.oebout(wire_pseudo_diffa_oebout[12:12]),
	.oein(wire_pseudo_diffa_oein[12:12]),
	.oeout(wire_pseudo_diffa_oeout[12:12])
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.dtcin(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	);
	cyclonev_pseudo_diff_out   pseudo_diffa_13
	( 
	.dtc(),
	.dtcbar(),
	.i(wire_pseudo_diffa_i[13:13]),
	.o(wire_pseudo_diffa_o[13:13]),
	.obar(wire_pseudo_diffa_obar[13:13]),
	.oebout(wire_pseudo_diffa_oebout[13:13]),
	.oein(wire_pseudo_diffa_oein[13:13]),
	.oeout(wire_pseudo_diffa_oeout[13:13])
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.dtcin(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	);
	cyclonev_pseudo_diff_out   pseudo_diffa_14
	( 
	.dtc(),
	.dtcbar(),
	.i(wire_pseudo_diffa_i[14:14]),
	.o(wire_pseudo_diffa_o[14:14]),
	.obar(wire_pseudo_diffa_obar[14:14]),
	.oebout(wire_pseudo_diffa_oebout[14:14]),
	.oein(wire_pseudo_diffa_oein[14:14]),
	.oeout(wire_pseudo_diffa_oeout[14:14])
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.dtcin(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	);
	cyclonev_pseudo_diff_out   pseudo_diffa_15
	( 
	.dtc(),
	.dtcbar(),
	.i(wire_pseudo_diffa_i[15:15]),
	.o(wire_pseudo_diffa_o[15:15]),
	.obar(wire_pseudo_diffa_obar[15:15]),
	.oebout(wire_pseudo_diffa_oebout[15:15]),
	.oein(wire_pseudo_diffa_oein[15:15]),
	.oeout(wire_pseudo_diffa_oeout[15:15])
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.dtcin(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	);
	cyclonev_pseudo_diff_out   pseudo_diffa_16
	( 
	.dtc(),
	.dtcbar(),
	.i(wire_pseudo_diffa_i[16:16]),
	.o(wire_pseudo_diffa_o[16:16]),
	.obar(wire_pseudo_diffa_obar[16:16]),
	.oebout(wire_pseudo_diffa_oebout[16:16]),
	.oein(wire_pseudo_diffa_oein[16:16]),
	.oeout(wire_pseudo_diffa_oeout[16:16])
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.dtcin(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	);
	assign
		wire_pseudo_diffa_i = datain,
		wire_pseudo_diffa_oein = {(~ oe_w[16]), (~ oe_w[15]), (~ oe_w[14]), (~ oe_w[13]), (~ oe_w[12]), (~ oe_w[11]), (~ oe_w[10]), (~ oe_w[9]), (~ oe_w[8]), (~ oe_w[7]), (~ oe_w[6]), (~ oe_w[5]), (~ oe_w[4]), (~ oe_w[3]), (~ oe_w[2]), (~ oe_w[1]), (~ oe_w[0])};
	assign
		dataout = wire_obufa_o,
		dataout_b = wire_obuf_ba_o,
		oe_w = {17{1'b1}};
endmodule //lvds_altiobuf17_o_iobuf_out_akt
//VALID FILE


// synopsys translate_off
`timescale 1 ps / 1 ps
// synopsys translate_on
module lvds_altiobuf17_o (
	datain,
	dataout,
	dataout_b);

	input	[16:0]  datain;
	output	[16:0]  dataout;
	output	[16:0]  dataout_b;

	wire [16:0] sub_wire0;
	wire [16:0] sub_wire1;
	wire [16:0] dataout = sub_wire0[16:0];
	wire [16:0] dataout_b = sub_wire1[16:0];

	lvds_altiobuf17_o_iobuf_out_akt	lvds_altiobuf17_o_iobuf_out_akt_component (
				.datain (datain),
				.dataout (sub_wire0),
				.dataout_b (sub_wire1));

endmodule

// ============================================================
// CNX file retrieval info
// ============================================================
// Retrieval info: PRIVATE: INTENDED_DEVICE_FAMILY STRING "Cyclone V"
// Retrieval info: PRIVATE: SYNTH_WRAPPER_GEN_POSTFIX STRING "0"
// Retrieval info: LIBRARY: altera_mf altera_mf.altera_mf_components.all
// Retrieval info: CONSTANT: INTENDED_DEVICE_FAMILY STRING "Cyclone V"
// Retrieval info: CONSTANT: enable_bus_hold STRING "FALSE"
// Retrieval info: CONSTANT: left_shift_series_termination_control STRING "FALSE"
// Retrieval info: CONSTANT: number_of_channels NUMERIC "17"
// Retrieval info: CONSTANT: open_drain_output STRING "FALSE"
// Retrieval info: CONSTANT: pseudo_differential_mode STRING "TRUE"
// Retrieval info: CONSTANT: use_differential_mode STRING "TRUE"
// Retrieval info: CONSTANT: use_oe STRING "FALSE"
// Retrieval info: CONSTANT: use_termination_control STRING "FALSE"
// Retrieval info: USED_PORT: datain 0 0 17 0 INPUT NODEFVAL "datain[16..0]"
// Retrieval info: USED_PORT: dataout 0 0 17 0 OUTPUT NODEFVAL "dataout[16..0]"
// Retrieval info: USED_PORT: dataout_b 0 0 17 0 OUTPUT NODEFVAL "dataout_b[16..0]"
// Retrieval info: CONNECT: @datain 0 0 17 0 datain 0 0 17 0
// Retrieval info: CONNECT: dataout 0 0 17 0 @dataout 0 0 17 0
// Retrieval info: CONNECT: dataout_b 0 0 17 0 @dataout_b 0 0 17 0
// Retrieval info: GEN_FILE: TYPE_NORMAL lvds_altiobuf17_o.v TRUE
// Retrieval info: GEN_FILE: TYPE_NORMAL lvds_altiobuf17_o.inc FALSE
// Retrieval info: GEN_FILE: TYPE_NORMAL lvds_altiobuf17_o.cmp FALSE
// Retrieval info: GEN_FILE: TYPE_NORMAL lvds_altiobuf17_o.bsf FALSE
// Retrieval info: GEN_FILE: TYPE_NORMAL lvds_altiobuf17_o_inst.v TRUE
// Retrieval info: GEN_FILE: TYPE_NORMAL lvds_altiobuf17_o_bb.v TRUE
// Retrieval info: LIB_FILE: cyclonev
